//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAS.Indicators.Technical.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATAS.Indicators.Technical.Properties.CustomResources", typeof(CustomResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a back above {0} @ {1}.
        /// </summary>
        public static string Alert_BackAbove {
            get {
                return ResourceManager.GetString("Alert_BackAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a back below {0} @ {1}.
        /// </summary>
        public static string Alert_BackBelow {
            get {
                return ResourceManager.GetString("Alert_BackBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a crossed above {0} @ {1}.
        /// </summary>
        public static string Alert_CrossedAbove {
            get {
                return ResourceManager.GetString("Alert_CrossedAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a crossed below {0} @ {1}.
        /// </summary>
        public static string Alert_CrossedBelow {
            get {
                return ResourceManager.GetString("Alert_CrossedBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum time between consecutive alerts on the same level price. Prevents alert storms when price oscillates around a level..
        /// </summary>
        public static string AlertCooldownSeconds_Description {
            get {
                return ResourceManager.GetString("AlertCooldownSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cooldown (seconds).
        /// </summary>
        public static string AlertCooldownSeconds_DisplayName {
            get {
                return ResourceManager.GetString("AlertCooldownSeconds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The .wav file name. Use defaults (&apos;alert1&apos;, &apos;alert2&apos;) or place custom files in the ATAS sounds folder..
        /// </summary>
        public static string AlertFile_Description {
            get {
                return ResourceManager.GetString("AlertFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert Sound File.
        /// </summary>
        public static string AlertFile_DisplayName {
            get {
                return ResourceManager.GetString("AlertFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filename of the sound played when an alert fires. ATAS resolves bundled names like &apos;alert1.wav&apos; from its sound directory; absolute paths work too..
        /// </summary>
        public static string AlertSoundFile_Description {
            get {
                return ResourceManager.GetString("AlertSoundFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound file.
        /// </summary>
        public static string AlertSoundFile_DisplayName {
            get {
                return ResourceManager.GetString("AlertSoundFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MenthorQ API key. When set together with User ID, the API becomes the active data source and manual text is ignored..
        /// </summary>
        public static string ApiKey_Description {
            get {
                return ResourceManager.GetString("ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a API Key.
        /// </summary>
        public static string ApiKey_DisplayName {
            get {
                return ResourceManager.GetString("ApiKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Applied to every API-fetched price BEFORE the offset. Most common case: ETF API feed → Futures chart. Approx ratios at current index levels: SPY → ES ≈ 10, QQQ → NQ ≈ 41, IWM → RTY ≈ 10. Ratios drift with index level — recalibrate periodically. Default 1 (no scaling). Applied at engine time — does not trigger an API refetch..
        /// </summary>
        public static string ApiMultiplier_Description {
            get {
                return ResourceManager.GetString("ApiMultiplier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplier (API to Chart).
        /// </summary>
        public static string ApiMultiplier_DisplayName {
            get {
                return ResourceManager.GetString("ApiMultiplier_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added to every API-fetched price AFTER the multiplier. Combined formula: (raw_price × multiplier) + offset. Applied at engine time — changing it does not trigger an API refetch..
        /// </summary>
        public static string ApiOffset_Description {
            get {
                return ResourceManager.GetString("ApiOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offset (API to Chart).
        /// </summary>
        public static string ApiOffset_DisplayName {
            get {
                return ResourceManager.GetString("ApiOffset_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for BL N lines, halos and labels..
        /// </summary>
        public static string BlindSpot_Description {
            get {
                return ResourceManager.GetString("BlindSpot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blind Spot.
        /// </summary>
        public static string BlindSpot_DisplayName {
            get {
                return ResourceManager.GetString("BlindSpot_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color for zones with buying dominance. Efficiency near 1 renders this color as pure; lower efficiency blends it toward the neutral color..
        /// </summary>
        public static string BuyColor_Description {
            get {
                return ResourceManager.GetString("BuyColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy Color.
        /// </summary>
        public static string BuyColor_DisplayName {
            get {
                return ResourceManager.GetString("BuyColor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for CR lines, halos and labels..
        /// </summary>
        public static string CallResistance_Description {
            get {
                return ResourceManager.GetString("CallResistance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Call Resistance.
        /// </summary>
        public static string CallResistance_DisplayName {
            get {
                return ResourceManager.GetString("CallResistance_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle to clear both Index and Futures text fields. Self-resets..
        /// </summary>
        public static string ClearManualTextNow_Description {
            get {
                return ResourceManager.GetString("ClearManualTextNow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear text fields.
        /// </summary>
        public static string ClearManualTextNow_DisplayName {
            get {
                return ResourceManager.GetString("ClearManualTextNow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lookback period used to compute the percentile threshold. Adapts to session volatility: short enough to track phase shifts, long enough to remain statistically stable..
        /// </summary>
        public static string ContextWindowMinutes_Description {
            get {
                return ResourceManager.GetString("ContextWindowMinutes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Context Window (minutes).
        /// </summary>
        public static string ContextWindowMinutes_DisplayName {
            get {
                return ResourceManager.GetString("ContextWindowMinutes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metric accumulated within the time window. Ticks: counts operations; Volume: sums contracts; Delta: net difference between buying and selling aggression; Buy/Sell Volume: isolate a single side..
        /// </summary>
        public static string DataType_Description {
            get {
                return ResourceManager.GetString("DataType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Type.
        /// </summary>
        public static string DataType_DisplayName {
            get {
                return ResourceManager.GetString("DataType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for 1D Max lines, halos and labels..
        /// </summary>
        public static string DayMax_Description {
            get {
                return ResourceManager.GetString("DayMax_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day Max.
        /// </summary>
        public static string DayMax_DisplayName {
            get {
                return ResourceManager.GetString("DayMax_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for 1D Min lines, halos and labels..
        /// </summary>
        public static string DayMin_Description {
            get {
                return ResourceManager.GetString("DayMin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day Min.
        /// </summary>
        public static string DayMin_DisplayName {
            get {
                return ResourceManager.GetString("DayMin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master switch for cross-level alerts. When off, nothing is emitted regardless of category visibility..
        /// </summary>
        public static string EnableAlerts_Description {
            get {
                return ResourceManager.GetString("EnableAlerts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable alerts.
        /// </summary>
        public static string EnableAlerts_DisplayName {
            get {
                return ResourceManager.GetString("EnableAlerts_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatically refresh API levels following MenthorQ&apos;s documented intraday schedule (14 fixed EST update slots: pre-market at 08:00 plus every 30 minutes from 09:50 to 15:50). A small post-slot delay lets the data settle on MenthorQ&apos;s end before the fetch fires. Toggling this on triggers an immediate catch-up fetch. EOD slots (18:30 / 23:00 EST) are not auto-refreshed; press Update Levels manually after market close if needed..
        /// </summary>
        public static string EnableAutoRefresh_Description {
            get {
                return ResourceManager.GetString("EnableAutoRefresh_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto refresh.
        /// </summary>
        public static string EnableAutoRefresh_DisplayName {
            get {
                return ResourceManager.GetString("EnableAutoRefresh_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renders a small status box in a corner of the chart showing internal indicator state: resolved ticker, active source, level/entry counts, pending alerts, API status, and current text/API multiplier+offset values. Default off — turn on when diagnosing why levels are missing or misaligned..
        /// </summary>
        public static string EnableDebugOverlay_Description {
            get {
                return ResourceManager.GetString("EnableDebugOverlay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show debug overlay.
        /// </summary>
        public static string EnableDebugOverlay_DisplayName {
            get {
                return ResourceManager.GetString("EnableDebugOverlay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable pasting MenthorQ levels as comma-separated text. Ignored when the API is configured and reachable..
        /// </summary>
        public static string EnableManualText_Description {
            get {
                return ResourceManager.GetString("EnableManualText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        public static string EnableManualText_DisplayName {
            get {
                return ResourceManager.GetString("EnableManualText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When a cross alert fires and price reverts back across the level within the cooldown window, emit a follow-up alert at cooldown expiry..
        /// </summary>
        public static string EnableReversalAlerts_Description {
            get {
                return ResourceManager.GetString("EnableReversalAlerts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert on reversal.
        /// </summary>
        public static string EnableReversalAlerts_DisplayName {
            get {
                return ResourceManager.GetString("EnableReversalAlerts_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of bars to the right drawn at full opacity. The horizontal line marks the center of the burst&apos;s price range as a transient support/resistance reference..
        /// </summary>
        public static string ExtensionBars_Description {
            get {
                return ResourceManager.GetString("ExtensionBars_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extension Bars (Full).
        /// </summary>
        public static string ExtensionBars_DisplayName {
            get {
                return ResourceManager.GetString("ExtensionBars_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of bars following the full-opacity segment drawn with linearly decreasing transparency (alpha). Set to 0 for an abrupt cutoff..
        /// </summary>
        public static string FadeBars_Description {
            get {
                return ResourceManager.GetString("FadeBars_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extension Bars (Fade).
        /// </summary>
        public static string FadeBars_DisplayName {
            get {
                return ResourceManager.GetString("FadeBars_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste MenthorQ output for the Futures ticker (ES / NQ / RTY). Offset is not applied to these prices..
        /// </summary>
        public static string FuturesTextRaw_Description {
            get {
                return ResourceManager.GetString("FuturesTextRaw_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Futures text.
        /// </summary>
        public static string FuturesTextRaw_DisplayName {
            get {
                return ResourceManager.GetString("FuturesTextRaw_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for GEX N lines, halos and labels..
        /// </summary>
        public static string GammaExposure_Description {
            get {
                return ResourceManager.GetString("GammaExposure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamma Exposure.
        /// </summary>
        public static string GammaExposure_DisplayName {
            get {
                return ResourceManager.GetString("GammaExposure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for GW lines, halos and labels..
        /// </summary>
        public static string GammaWall_Description {
            get {
                return ResourceManager.GetString("GammaWall_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamma Wall.
        /// </summary>
        public static string GammaWall_DisplayName {
            get {
                return ResourceManager.GetString("GammaWall_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highlights.
        /// </summary>
        public static string Group_Accents {
            get {
                return ResourceManager.GetString("Group_Accents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerts.
        /// </summary>
        public static string Group_Alerts {
            get {
                return ResourceManager.GetString("Group_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alpha tiers.
        /// </summary>
        public static string Group_AlphaTiers {
            get {
                return ResourceManager.GetString("Group_AlphaTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a API.
        /// </summary>
        public static string Group_Api {
            get {
                return ResourceManager.GetString("Group_Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculation.
        /// </summary>
        public static string Group_Calculation {
            get {
                return ResourceManager.GetString("Group_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data.
        /// </summary>
        public static string Group_Data {
            get {
                return ResourceManager.GetString("Group_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagnostics.
        /// </summary>
        public static string Group_Diagnostics {
            get {
                return ResourceManager.GetString("Group_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info Panel.
        /// </summary>
        public static string Group_InfoPanel {
            get {
                return ResourceManager.GetString("Group_InfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Levels.
        /// </summary>
        public static string Group_Levels {
            get {
                return ResourceManager.GetString("Group_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual text.
        /// </summary>
        public static string Group_ManualText {
            get {
                return ResourceManager.GetString("Group_ManualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line styles.
        /// </summary>
        public static string Group_Pens {
            get {
                return ResourceManager.GetString("Group_Pens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text.
        /// </summary>
        public static string Group_Text {
            get {
                return ResourceManager.GetString("Group_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Threshold.
        /// </summary>
        public static string Group_Threshold {
            get {
                return ResourceManager.GetString("Group_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visuals.
        /// </summary>
        public static string Group_Visuals {
            get {
                return ResourceManager.GetString("Group_Visuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Width tiers.
        /// </summary>
        public static string Group_WidthTiers {
            get {
                return ResourceManager.GetString("Group_WidthTiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for HVL lines, halos and labels..
        /// </summary>
        public static string HighVolatilityLevel_Description {
            get {
                return ResourceManager.GetString("HighVolatilityLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High Volatility Level.
        /// </summary>
        public static string HighVolatilityLevel_DisplayName {
            get {
                return ResourceManager.GetString("HighVolatilityLevel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste MenthorQ output for an Index or ETF ticker (SPX / NDX / RUT, or SPY / QQQ / IWM). Multiplier and offset below are applied to these prices in that order..
        /// </summary>
        public static string IndexTextRaw_Description {
            get {
                return ResourceManager.GetString("IndexTextRaw_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Index text.
        /// </summary>
        public static string IndexTextRaw_DisplayName {
            get {
                return ResourceManager.GetString("IndexTextRaw_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renders MenthorQ option-derived levels (Gamma Wall, Call Resistance, Put Support, etc.) on the chart, with sources from manual text paste or live API fetch, customizable visibility and color per category, cross-level alerts with reversal notifications, and an optional diagnostic overlay..
        /// </summary>
        public static string Indicator_Description {
            get {
                return ResourceManager.GetString("Indicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center.
        /// </summary>
        public static string LabelAlignment_Center {
            get {
                return ResourceManager.GetString("LabelAlignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bottom Left.
        /// </summary>
        public static string InfoPanelLocation_BottomLeft {
            get {
                return ResourceManager.GetString("InfoPanelLocation_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bottom Right.
        /// </summary>
        public static string InfoPanelLocation_BottomRight {
            get {
                return ResourceManager.GetString("InfoPanelLocation_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Left.
        /// </summary>
        public static string InfoPanelLocation_TopLeft {
            get {
                return ResourceManager.GetString("InfoPanelLocation_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Right.
        /// </summary>
        public static string InfoPanelLocation_TopRight {
            get {
                return ResourceManager.GetString("InfoPanelLocation_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chart corner where the info panel is anchored..
        /// </summary>
        public static string InfoPanelPosition_Description {
            get {
                return ResourceManager.GetString("InfoPanelPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Position.
        /// </summary>
        public static string InfoPanelPosition_DisplayName {
            get {
                return ResourceManager.GetString("InfoPanelPosition_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Where to anchor each level&apos;s text label horizontally. Right (default) keeps the previous behaviour — labels at the right edge of the chart area, just above the line. Center anchors them to the horizontal middle of the chart area, useful when the right side is busy with the price axis or a heavy DOM. Left anchors them to the left edge with a small padding. Pure visual change, no recalculation..
        /// </summary>
        public static string LabelAlignment_Description {
            get {
                return ResourceManager.GetString("LabelAlignment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left.
        /// </summary>
        public static string LabelAlignment_Left {
            get {
                return ResourceManager.GetString("LabelAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horizontal alignment.
        /// </summary>
        public static string LabelAlignment_Name {
            get {
                return ResourceManager.GetString("LabelAlignment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right.
        /// </summary>
        public static string LabelAlignment_Right {
            get {
                return ResourceManager.GetString("LabelAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Labels.
        /// </summary>
        public static string Labels_Header {
            get {
                return ResourceManager.GetString("Labels_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear text now.
        /// </summary>
        public static string LevelsLolo_ClearTextNow_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_ClearTextNow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draws SpotGamma-style option levels (Combo, Large Gamma, Volatility Trigger, Call Wall, Put Wall, Zero Gamma) derived from comma-separated text. Features configurable line styles per category, rank-based width and opacity tiers, optional cyan halo for 0DTE labels, and a dotted highlight for high-priority 0DTE levels (LG/PW/CW within the thick tier)..
        /// </summary>
        public static string LevelsLolo_Description {
            get {
                return ResourceManager.GetString("LevelsLolo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable 0DTE halo.
        /// </summary>
        public static string LevelsLolo_Enable0DTEHalo_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_Enable0DTEHalo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font size.
        /// </summary>
        public static string LevelsLolo_FontSize_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_FontSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0DTE halo opacity (0-255).
        /// </summary>
        public static string LevelsLolo_HaloAlpha_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_HaloAlpha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0DTE halo extra width (px).
        /// </summary>
        public static string LevelsLolo_HaloExtraWidth_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_HaloExtraWidth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extend to the last visible bar instead of the right chart edge..
        /// </summary>
        public static string LevelsLolo_LastBarOnly_Description {
            get {
                return ResourceManager.GetString("LevelsLolo_LastBarOnly_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last bar only.
        /// </summary>
        public static string LevelsLolo_LastBarOnly_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_LastBarOnly_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opacity (medium).
        /// </summary>
        public static string LevelsLolo_MediumAlpha_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_MediumAlpha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium up to rank.
        /// </summary>
        public static string LevelsLolo_MediumMaxRank_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_MediumMaxRank_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Width (medium).
        /// </summary>
        public static string LevelsLolo_MediumWidth_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_MediumWidth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offset X.
        /// </summary>
        public static string LevelsLolo_OffsetX_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_OffsetX_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offset Y.
        /// </summary>
        public static string LevelsLolo_OffsetY_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_OffsetY_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0DTE halo style.
        /// </summary>
        public static string LevelsLolo_Pen0DTEHalo_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_Pen0DTEHalo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Call Wall (CW).
        /// </summary>
        public static string LevelsLolo_PenCallWall_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_PenCallWall_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combo (CO).
        /// </summary>
        public static string LevelsLolo_PenCombo_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_PenCombo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Large Gamma (LG).
        /// </summary>
        public static string LevelsLolo_PenLargeGamma_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_PenLargeGamma_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other / Unknown.
        /// </summary>
        public static string LevelsLolo_PenOther_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_PenOther_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put Wall (PW).
        /// </summary>
        public static string LevelsLolo_PenPutWall_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_PenPutWall_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volatility Trigger (VT).
        /// </summary>
        public static string LevelsLolo_PenVolTrigger_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_PenVolTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zero Gamma (ZG).
        /// </summary>
        public static string LevelsLolo_PenZeroGamma_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_PenZeroGamma_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Example: $SP: CO44, 7073, LG07, 7048, ....
        /// </summary>
        public static string LevelsLolo_RawText_Description {
            get {
                return ResourceManager.GetString("LevelsLolo_RawText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raw text.
        /// </summary>
        public static string LevelsLolo_RawText_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_RawText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right-aligned text.
        /// </summary>
        public static string LevelsLolo_RightAligned_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_RightAligned_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opacity (thick).
        /// </summary>
        public static string LevelsLolo_ThickAlpha_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_ThickAlpha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thick up to rank.
        /// </summary>
        public static string LevelsLolo_ThickMaxRank_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_ThickMaxRank_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Width (thick).
        /// </summary>
        public static string LevelsLolo_ThickWidth_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_ThickWidth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opacity (thin).
        /// </summary>
        public static string LevelsLolo_ThinAlpha_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_ThinAlpha_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Width (thin).
        /// </summary>
        public static string LevelsLolo_ThinWidth_DisplayName {
            get {
                return ResourceManager.GetString("LevelsLolo_ThinWidth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for LB lines, halos and labels..
        /// </summary>
        public static string LowerBand_Description {
            get {
                return ResourceManager.GetString("LowerBand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lower Band.
        /// </summary>
        public static string LowerBand_DisplayName {
            get {
                return ResourceManager.GetString("LowerBand_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of recent bursts visible in the panel. Older events are automatically removed as new data arrives..
        /// </summary>
        public static string MaxEventsInPanel_Description {
            get {
                return ResourceManager.GetString("MaxEventsInPanel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max Events Shown.
        /// </summary>
        public static string MaxEventsInPanel_DisplayName {
            get {
                return ResourceManager.GetString("MaxEventsInPanel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color used when a burst is balanced (efficiency below 0.3) or as the base for low-efficiency directional blends..
        /// </summary>
        public static string NeutralColor_Description {
            get {
                return ResourceManager.GetString("NeutralColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral Color.
        /// </summary>
        public static string NeutralColor_DisplayName {
            get {
                return ResourceManager.GetString("NeutralColor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for fallback / unrecognised labels..
        /// </summary>
        public static string Other_Description {
            get {
                return ResourceManager.GetString("Other_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        public static string Other_DisplayName {
            get {
                return ResourceManager.GetString("Other_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bottom Center.
        /// </summary>
        public static string OverlayLocation_BottomCenter {
            get {
                return ResourceManager.GetString("OverlayLocation_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bottom Left.
        /// </summary>
        public static string OverlayLocation_BottomLeft {
            get {
                return ResourceManager.GetString("OverlayLocation_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bottom Right.
        /// </summary>
        public static string OverlayLocation_BottomRight {
            get {
                return ResourceManager.GetString("OverlayLocation_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corner of the chart where the debug overlay is anchored. Default TopRight to avoid colliding with the OHLC info that ATAS draws in the top-left under the cursor..
        /// </summary>
        public static string OverlayLocation_Description {
            get {
                return ResourceManager.GetString("OverlayLocation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overlay location.
        /// </summary>
        public static string OverlayLocation_DisplayName {
            get {
                return ResourceManager.GetString("OverlayLocation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Center.
        /// </summary>
        public static string OverlayLocation_TopCenter {
            get {
                return ResourceManager.GetString("OverlayLocation_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Left.
        /// </summary>
        public static string OverlayLocation_TopLeft {
            get {
                return ResourceManager.GetString("OverlayLocation_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Right.
        /// </summary>
        public static string OverlayLocation_TopRight {
            get {
                return ResourceManager.GetString("OverlayLocation_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for PS lines, halos and labels..
        /// </summary>
        public static string PutSupport_Description {
            get {
                return ResourceManager.GetString("PutSupport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put Support.
        /// </summary>
        public static string PutSupport_DisplayName {
            get {
                return ResourceManager.GetString("PutSupport_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for RT lines, halos and labels..
        /// </summary>
        public static string RiskTrigger_Description {
            get {
                return ResourceManager.GetString("RiskTrigger_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Risk Trigger.
        /// </summary>
        public static string RiskTrigger_DisplayName {
            get {
                return ResourceManager.GetString("RiskTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color for zones with selling dominance. Efficiency near 1 renders this color as pure; lower efficiency blends it toward the neutral color..
        /// </summary>
        public static string SellColor_Description {
            get {
                return ResourceManager.GetString("SellColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell Color.
        /// </summary>
        public static string SellColor_DisplayName {
            get {
                return ResourceManager.GetString("SellColor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle the floating panel that lists the most recent burst events and their metrics..
        /// </summary>
        public static string ShowInfoPanel_Description {
            get {
                return ResourceManager.GetString("ShowInfoPanel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Info Panel.
        /// </summary>
        public static string ShowInfoPanel_DisplayName {
            get {
                return ResourceManager.GetString("ShowInfoPanel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum time between alerts to prevent notification spam. Set to 0 to receive all alerts without restriction..
        /// </summary>
        public static string SpeedOfTapeV3_AlertCooldownSeconds_Description {
            get {
                return ResourceManager.GetString("SpeedOfTapeV3_AlertCooldownSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert Cooldown (seconds).
        /// </summary>
        public static string SpeedOfTapeV3_AlertCooldownSeconds_DisplayName {
            get {
                return ResourceManager.GetString("SpeedOfTapeV3_AlertCooldownSeconds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Event-driven tape speed detector. Dynamic histogram with High Water Mark (HWM) frozen bars color-coded by burst direction. Features a dynamic percentile-based threshold, persistent price-panel zones with fading extension lines, and a floating info panel with real-time metrics..
        /// </summary>
        public static string SpeedOfTapeV3_Description {
            get {
                return ResourceManager.GetString("SpeedOfTapeV3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy Volume.
        /// </summary>
        public static string SpeedType_Buys {
            get {
                return ResourceManager.GetString("SpeedType_Buys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delta (Aggression).
        /// </summary>
        public static string SpeedType_Delta {
            get {
                return ResourceManager.GetString("SpeedType_Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sell Volume.
        /// </summary>
        public static string SpeedType_Sells {
            get {
                return ResourceManager.GetString("SpeedType_Sells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ticks (HFT).
        /// </summary>
        public static string SpeedType_Ticks {
            get {
                return ResourceManager.GetString("SpeedType_Ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume (Blocks).
        /// </summary>
        public static string SpeedType_Volume {
            get {
                return ResourceManager.GetString("SpeedType_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string Style_Color_DisplayName {
            get {
                return ResourceManager.GetString("Style_Color_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hidden.
        /// </summary>
        public static string Style_State_Hidden {
            get {
                return ResourceManager.GetString("Style_State_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visible.
        /// </summary>
        public static string Style_State_Visible {
            get {
                return ResourceManager.GetString("Style_State_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visible.
        /// </summary>
        public static string Style_Visible_DisplayName {
            get {
                return ResourceManager.GetString("Style_Visible_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for Swing lines, halos and labels..
        /// </summary>
        public static string Swing_Description {
            get {
                return ResourceManager.GetString("Swing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Swing.
        /// </summary>
        public static string Swing_DisplayName {
            get {
                return ResourceManager.GetString("Swing_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Applied to every Index-text price BEFORE the offset. Most common case: ETF data → Futures chart. Approx ratios at current index levels: SPY → ES ≈ 10, QQQ → NQ ≈ 41, IWM → RTY ≈ 10. Ratios drift with index level — recalibrate periodically. Default 1 (no scaling). Futures text is never transformed..
        /// </summary>
        public static string TextMultiplier_Description {
            get {
                return ResourceManager.GetString("TextMultiplier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplier (Index to Chart).
        /// </summary>
        public static string TextMultiplier_DisplayName {
            get {
                return ResourceManager.GetString("TextMultiplier_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added to every price parsed from the Index text, to align SPX levels to ES, NDX to NQ, etc. Futures text is never offset..
        /// </summary>
        public static string TextOffset_Description {
            get {
                return ResourceManager.GetString("TextOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offset (Index to Chart).
        /// </summary>
        public static string TextOffset_DisplayName {
            get {
                return ResourceManager.GetString("TextOffset_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speed level above which a burst is detected. P95 represents speeds occurring only 5% of the time in the recent context. Higher values increase selectivity..
        /// </summary>
        public static string ThresholdPercentile_Description {
            get {
                return ResourceManager.GetString("ThresholdPercentile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Threshold Percentile.
        /// </summary>
        public static string ThresholdPercentile_DisplayName {
            get {
                return ResourceManager.GetString("ThresholdPercentile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optional. Leave empty to use the chart instrument (micros are auto-stripped: MES→ES, MNQ→NQ). Set a value to force a specific ticker (e.g. SPX on ES, or ES when the feed exposes ESH24)..
        /// </summary>
        public static string TickerOverride_Description {
            get {
                return ResourceManager.GetString("TickerOverride_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ticker override.
        /// </summary>
        public static string TickerOverride_DisplayName {
            get {
                return ResourceManager.GetString("TickerOverride_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length of the sliding window used to calculate speed. Smaller values increase reactivity but add noise; larger values smooth out micro-bursts..
        /// </summary>
        public static string TimeWindow_Description {
            get {
                return ResourceManager.GetString("TimeWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time Window (seconds).
        /// </summary>
        public static string TimeWindow_DisplayName {
            get {
                return ResourceManager.GetString("TimeWindow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fetch latest levels from the MenthorQ API. Self-resets..
        /// </summary>
        public static string UpdateLevels_Description {
            get {
                return ResourceManager.GetString("UpdateLevels_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Levels.
        /// </summary>
        public static string UpdateLevels_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLevels_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for UB lines, halos and labels..
        /// </summary>
        public static string UpperBand_Description {
            get {
                return ResourceManager.GetString("UpperBand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upper Band.
        /// </summary>
        public static string UpperBand_DisplayName {
            get {
                return ResourceManager.GetString("UpperBand_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master switch for audio and popup notifications on detected bursts. Disabled by default..
        /// </summary>
        public static string UseAlerts_Description {
            get {
                return ResourceManager.GetString("UseAlerts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable Alerts.
        /// </summary>
        public static string UseAlerts_DisplayName {
            get {
                return ResourceManager.GetString("UseAlerts_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email associated with your MenthorQ account. Sent as the user_id query parameter on every request..
        /// </summary>
        public static string UserId_Description {
            get {
                return ResourceManager.GetString("UserId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User ID (email).
        /// </summary>
        public static string UserId_DisplayName {
            get {
                return ResourceManager.GetString("UserId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Defines how burst zones appear on the price chart. &apos;All events&apos; shows every detection; &apos;Primary only&apos; highlights only the highest-speed burst per bar; &apos;Hidden&apos; disables the price overlay..
        /// </summary>
        public static string ZoneDisplay_Description {
            get {
                return ResourceManager.GetString("ZoneDisplay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zone Display.
        /// </summary>
        public static string ZoneDisplay_DisplayName {
            get {
                return ResourceManager.GetString("ZoneDisplay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Events.
        /// </summary>
        public static string ZoneDisplayMode_All {
            get {
                return ResourceManager.GetString("ZoneDisplayMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hidden.
        /// </summary>
        public static string ZoneDisplayMode_Hidden {
            get {
                return ResourceManager.GetString("ZoneDisplayMode_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primary Only.
        /// </summary>
        public static string ZoneDisplayMode_PrimaryOnly {
            get {
                return ResourceManager.GetString("ZoneDisplayMode_PrimaryOnly", resourceCulture);
            }
        }
    }
}
