//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATAS.Indicators.Technical.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATAS.Indicators.Technical.Properties.CustomResources", typeof(CustomResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a back above {0} @ {1}.
        /// </summary>
        public static string Alert_BackAbove {
            get {
                return ResourceManager.GetString("Alert_BackAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a back below {0} @ {1}.
        /// </summary>
        public static string Alert_BackBelow {
            get {
                return ResourceManager.GetString("Alert_BackBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a crossed above {0} @ {1}.
        /// </summary>
        public static string Alert_CrossedAbove {
            get {
                return ResourceManager.GetString("Alert_CrossedAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a crossed below {0} @ {1}.
        /// </summary>
        public static string Alert_CrossedBelow {
            get {
                return ResourceManager.GetString("Alert_CrossedBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum time between consecutive alerts on the same level price. Prevents alert storms when price oscillates around a level..
        /// </summary>
        public static string AlertCooldownSeconds_Description {
            get {
                return ResourceManager.GetString("AlertCooldownSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cooldown (seconds).
        /// </summary>
        public static string AlertCooldownSeconds_DisplayName {
            get {
                return ResourceManager.GetString("AlertCooldownSeconds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filename of the sound played when an alert fires. ATAS resolves bundled names like &apos;alert1.wav&apos; from its sound directory; absolute paths work too..
        /// </summary>
        public static string AlertSoundFile_Description {
            get {
                return ResourceManager.GetString("AlertSoundFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound file.
        /// </summary>
        public static string AlertSoundFile_DisplayName {
            get {
                return ResourceManager.GetString("AlertSoundFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MenthorQ API key. When set together with User ID, the API becomes the active data source and manual text is ignored..
        /// </summary>
        public static string ApiKey_Description {
            get {
                return ResourceManager.GetString("ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a API Key.
        /// </summary>
        public static string ApiKey_DisplayName {
            get {
                return ResourceManager.GetString("ApiKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Applied to every API-fetched price BEFORE the offset. Most common case: ETF API feed → Futures chart. Approx ratios at current index levels: SPY → ES ≈ 10, QQQ → NQ ≈ 41, IWM → RTY ≈ 10. Ratios drift with index level — recalibrate periodically. Default 1 (no scaling). Applied at engine time — does not trigger an API refetch..
        /// </summary>
        public static string ApiMultiplier_Description {
            get {
                return ResourceManager.GetString("ApiMultiplier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplier (API to Chart).
        /// </summary>
        public static string ApiMultiplier_DisplayName {
            get {
                return ResourceManager.GetString("ApiMultiplier_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added to every API-fetched price AFTER the multiplier. Combined formula: (raw_price × multiplier) + offset. Applied at engine time — changing it does not trigger an API refetch..
        /// </summary>
        public static string ApiOffset_Description {
            get {
                return ResourceManager.GetString("ApiOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offset (API to Chart).
        /// </summary>
        public static string ApiOffset_DisplayName {
            get {
                return ResourceManager.GetString("ApiOffset_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for BL N lines, halos and labels..
        /// </summary>
        public static string BlindSpot_Description {
            get {
                return ResourceManager.GetString("BlindSpot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blind Spot.
        /// </summary>
        public static string BlindSpot_DisplayName {
            get {
                return ResourceManager.GetString("BlindSpot_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for CR lines, halos and labels..
        /// </summary>
        public static string CallResistance_Description {
            get {
                return ResourceManager.GetString("CallResistance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Call Resistance.
        /// </summary>
        public static string CallResistance_DisplayName {
            get {
                return ResourceManager.GetString("CallResistance_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle to clear both Index and Futures text fields. Self-resets..
        /// </summary>
        public static string ClearManualTextNow_Description {
            get {
                return ResourceManager.GetString("ClearManualTextNow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear text fields.
        /// </summary>
        public static string ClearManualTextNow_DisplayName {
            get {
                return ResourceManager.GetString("ClearManualTextNow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for 1D Max lines, halos and labels..
        /// </summary>
        public static string DayMax_Description {
            get {
                return ResourceManager.GetString("DayMax_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day Max.
        /// </summary>
        public static string DayMax_DisplayName {
            get {
                return ResourceManager.GetString("DayMax_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for 1D Min lines, halos and labels..
        /// </summary>
        public static string DayMin_Description {
            get {
                return ResourceManager.GetString("DayMin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day Min.
        /// </summary>
        public static string DayMin_DisplayName {
            get {
                return ResourceManager.GetString("DayMin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Master switch for cross-level alerts. When off, nothing is emitted regardless of category visibility..
        /// </summary>
        public static string EnableAlerts_Description {
            get {
                return ResourceManager.GetString("EnableAlerts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable alerts.
        /// </summary>
        public static string EnableAlerts_DisplayName {
            get {
                return ResourceManager.GetString("EnableAlerts_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatically refresh API levels following MenthorQ&apos;s documented intraday schedule (14 fixed EST update slots: pre-market at 08:00 plus every 30 minutes from 09:50 to 15:50). A small post-slot delay lets the data settle on MenthorQ&apos;s end before the fetch fires. Toggling this on triggers an immediate catch-up fetch. EOD slots (18:30 / 23:00 EST) are not auto-refreshed; press Update Levels manually after market close if needed..
        /// </summary>
        public static string EnableAutoRefresh_Description {
            get {
                return ResourceManager.GetString("EnableAutoRefresh_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto refresh.
        /// </summary>
        public static string EnableAutoRefresh_DisplayName {
            get {
                return ResourceManager.GetString("EnableAutoRefresh_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renders a small status box in a corner of the chart showing internal indicator state: resolved ticker, active source, level/entry counts, pending alerts, API status, and current text/API multiplier+offset values. Default off — turn on when diagnosing why levels are missing or misaligned..
        /// </summary>
        public static string EnableDebugOverlay_Description {
            get {
                return ResourceManager.GetString("EnableDebugOverlay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show debug overlay.
        /// </summary>
        public static string EnableDebugOverlay_DisplayName {
            get {
                return ResourceManager.GetString("EnableDebugOverlay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable pasting MenthorQ levels as comma-separated text. Ignored when the API is configured and reachable..
        /// </summary>
        public static string EnableManualText_Description {
            get {
                return ResourceManager.GetString("EnableManualText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        public static string EnableManualText_DisplayName {
            get {
                return ResourceManager.GetString("EnableManualText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When a cross alert fires and price reverts back across the level within the cooldown window, emit a follow-up alert at cooldown expiry..
        /// </summary>
        public static string EnableReversalAlerts_Description {
            get {
                return ResourceManager.GetString("EnableReversalAlerts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert on reversal.
        /// </summary>
        public static string EnableReversalAlerts_DisplayName {
            get {
                return ResourceManager.GetString("EnableReversalAlerts_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste MenthorQ output for the Futures ticker (ES / NQ / RTY). Offset is not applied to these prices..
        /// </summary>
        public static string FuturesTextRaw_Description {
            get {
                return ResourceManager.GetString("FuturesTextRaw_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Futures text.
        /// </summary>
        public static string FuturesTextRaw_DisplayName {
            get {
                return ResourceManager.GetString("FuturesTextRaw_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for GEX N lines, halos and labels..
        /// </summary>
        public static string GammaExposure_Description {
            get {
                return ResourceManager.GetString("GammaExposure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamma Exposure.
        /// </summary>
        public static string GammaExposure_DisplayName {
            get {
                return ResourceManager.GetString("GammaExposure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for GW lines, halos and labels..
        /// </summary>
        public static string GammaWall_Description {
            get {
                return ResourceManager.GetString("GammaWall_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gamma Wall.
        /// </summary>
        public static string GammaWall_DisplayName {
            get {
                return ResourceManager.GetString("GammaWall_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerts.
        /// </summary>
        public static string Group_Alerts {
            get {
                return ResourceManager.GetString("Group_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a API.
        /// </summary>
        public static string Group_Api {
            get {
                return ResourceManager.GetString("Group_Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diagnostics.
        /// </summary>
        public static string Group_Diagnostics {
            get {
                return ResourceManager.GetString("Group_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Levels.
        /// </summary>
        public static string Group_Levels {
            get {
                return ResourceManager.GetString("Group_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual text.
        /// </summary>
        public static string Group_ManualText {
            get {
                return ResourceManager.GetString("Group_ManualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for HVL lines, halos and labels..
        /// </summary>
        public static string HighVolatilityLevel_Description {
            get {
                return ResourceManager.GetString("HighVolatilityLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High Volatility Level.
        /// </summary>
        public static string HighVolatilityLevel_DisplayName {
            get {
                return ResourceManager.GetString("HighVolatilityLevel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste MenthorQ output for an Index or ETF ticker (SPX / NDX / RUT, or SPY / QQQ / IWM). Multiplier and offset below are applied to these prices in that order..
        /// </summary>
        public static string IndexTextRaw_Description {
            get {
                return ResourceManager.GetString("IndexTextRaw_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Index text.
        /// </summary>
        public static string IndexTextRaw_DisplayName {
            get {
                return ResourceManager.GetString("IndexTextRaw_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renders MenthorQ option-derived levels (Gamma Wall, Call Resistance, Put Support, etc.) on the chart, with sources from manual text paste or live API fetch, customizable visibility and color per category, cross-level alerts with reversal notifications, and an optional diagnostic overlay..
        /// </summary>
        public static string Indicator_Description {
            get {
                return ResourceManager.GetString("Indicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center.
        /// </summary>
        public static string LabelAlignment_Center {
            get {
                return ResourceManager.GetString("LabelAlignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Where to anchor each level&apos;s text label horizontally. Right (default) keeps the previous behaviour — labels at the right edge of the chart area, just above the line. Center anchors them to the horizontal middle of the chart area, useful when the right side is busy with the price axis or a heavy DOM. Left anchors them to the left edge with a small padding. Pure visual change, no recalculation..
        /// </summary>
        public static string LabelAlignment_Description {
            get {
                return ResourceManager.GetString("LabelAlignment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left.
        /// </summary>
        public static string LabelAlignment_Left {
            get {
                return ResourceManager.GetString("LabelAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horizontal alignment.
        /// </summary>
        public static string LabelAlignment_Name {
            get {
                return ResourceManager.GetString("LabelAlignment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right.
        /// </summary>
        public static string LabelAlignment_Right {
            get {
                return ResourceManager.GetString("LabelAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Labels.
        /// </summary>
        public static string Labels_Header {
            get {
                return ResourceManager.GetString("Labels_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for LB lines, halos and labels..
        /// </summary>
        public static string LowerBand_Description {
            get {
                return ResourceManager.GetString("LowerBand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lower Band.
        /// </summary>
        public static string LowerBand_DisplayName {
            get {
                return ResourceManager.GetString("LowerBand_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for fallback / unrecognised labels..
        /// </summary>
        public static string Other_Description {
            get {
                return ResourceManager.GetString("Other_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        public static string Other_DisplayName {
            get {
                return ResourceManager.GetString("Other_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bottom Center.
        /// </summary>
        public static string OverlayLocation_BottomCenter {
            get {
                return ResourceManager.GetString("OverlayLocation_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bottom Left.
        /// </summary>
        public static string OverlayLocation_BottomLeft {
            get {
                return ResourceManager.GetString("OverlayLocation_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bottom Right.
        /// </summary>
        public static string OverlayLocation_BottomRight {
            get {
                return ResourceManager.GetString("OverlayLocation_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corner of the chart where the debug overlay is anchored. Default TopRight to avoid colliding with the OHLC info that ATAS draws in the top-left under the cursor..
        /// </summary>
        public static string OverlayLocation_Description {
            get {
                return ResourceManager.GetString("OverlayLocation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overlay location.
        /// </summary>
        public static string OverlayLocation_DisplayName {
            get {
                return ResourceManager.GetString("OverlayLocation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Center.
        /// </summary>
        public static string OverlayLocation_TopCenter {
            get {
                return ResourceManager.GetString("OverlayLocation_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Left.
        /// </summary>
        public static string OverlayLocation_TopLeft {
            get {
                return ResourceManager.GetString("OverlayLocation_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Right.
        /// </summary>
        public static string OverlayLocation_TopRight {
            get {
                return ResourceManager.GetString("OverlayLocation_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for PS lines, halos and labels..
        /// </summary>
        public static string PutSupport_Description {
            get {
                return ResourceManager.GetString("PutSupport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put Support.
        /// </summary>
        public static string PutSupport_DisplayName {
            get {
                return ResourceManager.GetString("PutSupport_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for RT lines, halos and labels..
        /// </summary>
        public static string RiskTrigger_Description {
            get {
                return ResourceManager.GetString("RiskTrigger_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Risk Trigger.
        /// </summary>
        public static string RiskTrigger_DisplayName {
            get {
                return ResourceManager.GetString("RiskTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string Style_Color_DisplayName {
            get {
                return ResourceManager.GetString("Style_Color_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hidden.
        /// </summary>
        public static string Style_State_Hidden {
            get {
                return ResourceManager.GetString("Style_State_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visible.
        /// </summary>
        public static string Style_State_Visible {
            get {
                return ResourceManager.GetString("Style_State_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visible.
        /// </summary>
        public static string Style_Visible_DisplayName {
            get {
                return ResourceManager.GetString("Style_Visible_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for Swing lines, halos and labels..
        /// </summary>
        public static string Swing_Description {
            get {
                return ResourceManager.GetString("Swing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Swing.
        /// </summary>
        public static string Swing_DisplayName {
            get {
                return ResourceManager.GetString("Swing_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Applied to every Index-text price BEFORE the offset. Most common case: ETF data → Futures chart. Approx ratios at current index levels: SPY → ES ≈ 10, QQQ → NQ ≈ 41, IWM → RTY ≈ 10. Ratios drift with index level — recalibrate periodically. Default 1 (no scaling). Futures text is never transformed..
        /// </summary>
        public static string TextMultiplier_Description {
            get {
                return ResourceManager.GetString("TextMultiplier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplier (Index to Chart).
        /// </summary>
        public static string TextMultiplier_DisplayName {
            get {
                return ResourceManager.GetString("TextMultiplier_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added to every price parsed from the Index text, to align SPX levels to ES, NDX to NQ, etc. Futures text is never offset..
        /// </summary>
        public static string TextOffset_Description {
            get {
                return ResourceManager.GetString("TextOffset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offset (Index to Chart).
        /// </summary>
        public static string TextOffset_DisplayName {
            get {
                return ResourceManager.GetString("TextOffset_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optional. Leave empty to use the chart instrument (micros are auto-stripped: MES→ES, MNQ→NQ). Set a value to force a specific ticker (e.g. SPX on ES, or ES when the feed exposes ESH24)..
        /// </summary>
        public static string TickerOverride_Description {
            get {
                return ResourceManager.GetString("TickerOverride_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ticker override.
        /// </summary>
        public static string TickerOverride_DisplayName {
            get {
                return ResourceManager.GetString("TickerOverride_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fetch latest levels from the MenthorQ API. Self-resets..
        /// </summary>
        public static string UpdateLevels_Description {
            get {
                return ResourceManager.GetString("UpdateLevels_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Levels.
        /// </summary>
        public static string UpdateLevels_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLevels_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility and color for UB lines, halos and labels..
        /// </summary>
        public static string UpperBand_Description {
            get {
                return ResourceManager.GetString("UpperBand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upper Band.
        /// </summary>
        public static string UpperBand_DisplayName {
            get {
                return ResourceManager.GetString("UpperBand_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email associated with your MenthorQ account. Sent as the user_id query parameter on every request..
        /// </summary>
        public static string UserId_Description {
            get {
                return ResourceManager.GetString("UserId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User ID (email).
        /// </summary>
        public static string UserId_DisplayName {
            get {
                return ResourceManager.GetString("UserId_DisplayName", resourceCulture);
            }
        }
    }
}
