#!/usr/bin/env python3
"""Generate Technical/Compat/Localization/PlatformStrings.* from an ATAS install.

Why
---
Upstream indicators reference OFT.Localization.Strings keys that older SDKs
(Stable, Latest, Beta, ATAS X Beta) do not ship yet. Instead of rerouting every
call site, non-Alpha builds replace `Strings` with a generated class that has
the same key names and carries its own resources. The generated class is
declared as `Strings` inside the indicators' namespace, so C# name lookup finds
it before the `using OFT.Localization;` directive of each file; sub-namespaces
and other namespaces that use `Strings` get a small forwarding class.
Alpha builds keep using the platform class.

Only the keys actually referenced by Technical/**/*.cs are generated, so the
resources stay small. Re-run this script whenever a build fails with
"'Strings' does not contain a definition for 'X'" on a non-Alpha flavor.

Usage
-----
    # Source = the most complete SDK (Alpha), decompiled on the fly with ilspycmd:
    python tools/localization/generate_platform_strings.py --atas "C:\\Program Files (x86)\\ATAS Platform"

    # Or from resx files already extracted with `ilspycmd -p`:
    python tools/localization/generate_platform_strings.py --resx-dir path/to/extracted

Requires ilspycmd on PATH for --atas (dotnet tool install -g ilspycmd --version 9.1.0.7988).
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.sax.saxutils import escape

REPO = Path(__file__).resolve().parents[2]
TECHNICAL = REPO / "Technical"
OUT_DIR = TECHNICAL / "Compat" / "Localization"
RESX_NAME = "PlatformStrings"
CODE_FILE = "PlatformStrings.Generated.cs"
ROOT_NS = "ATAS.Indicators.Technical"
MANIFEST = f"{ROOT_NS}.Compat.Localization.{RESX_NAME}"
NS_RE = re.compile(r"^\s*namespace\s+([A-Za-z0-9_.]+)", re.M)
BASE_NAME = "OFT.Localization.Strings"
KEY_RE = re.compile(r"(?<![A-Za-z0-9_.])Strings\.([A-Za-z_][A-Za-z0-9_]*)")

RESX_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""


def used_keys() -> dict[str, set[str]]:
    """Keys referenced per namespace."""
    by_ns: dict[str, set[str]] = {}
    for cs in TECHNICAL.rglob("*.cs"):
        if OUT_DIR in cs.parents or "obj" in cs.parts or "bin" in cs.parts:
            continue
        text = cs.read_text(encoding="utf-8-sig", errors="replace")
        keys = set(KEY_RE.findall(text))
        if not keys:
            continue
        m = NS_RE.search(text)
        by_ns.setdefault(m.group(1) if m else "", set()).update(keys)
    return by_ns


def extract_from_install(atas: Path, work: Path) -> Path:
    if shutil.which("ilspycmd") is None:
        sys.exit("ilspycmd not found on PATH")
    out = work / "resx"
    out.mkdir(parents=True)
    dlls = [atas / "OFT.Localization.dll"] + sorted(atas.glob("*/OFT.Localization.resources.dll"))
    for i, dll in enumerate(dlls):
        target = work / f"p{i}"
        subprocess.run(["ilspycmd", "-p", "-o", str(target), str(dll)], check=True, capture_output=True)
        for resx in target.rglob(f"{BASE_NAME}*.resx"):
            shutil.copy(resx, out / resx.name)
    return out


def read_resx(path: Path) -> dict[str, str]:
    data = {}
    for node in ET.parse(path).getroot().iter("data"):
        value = node.find("value")
        if node.get("type") is None and value is not None:
            data[node.get("name")] = value.text or ""
    return data


def write_resx(path: Path, entries: dict[str, str]) -> None:
    lines = [RESX_HEADER]
    for key in sorted(entries):
        lines.append(f'  <data name="{escape(key)}" xml:space="preserve"><value>{escape(entries[key])}</value></data>\n')
    lines.append("</root>\n")
    path.write_text("".join(lines), encoding="utf-8", newline="\n")


def write_code(path: Path, by_ns: dict[str, set[str]], keys: list[str]) -> None:
    def prop(k: str, body: str) -> str:
        return f"\tpublic static string {k} => {body};\n"

    main = "".join(prop(k, f'ResourceManager.GetString("{k}", resourceCulture)') for k in keys)
    parts = [f"""// <auto-generated>
// Generated by tools/localization/generate_platform_strings.py. Do not edit by hand.
// </auto-generated>
#if !(ATAS_ALPHA || ATAS_X_ALPHA)
namespace {ROOT_NS}
{{
using System.ComponentModel;
using System.Globalization;
using System.Resources;

/// <summary>
/// Stand-in for OFT.Localization.Strings on SDKs that lack some of the keys used by the indicators.
/// Holds only the keys referenced by this project, with texts taken from the Alpha SDK.
/// </summary>
internal static class Strings
{{
\tprivate static ResourceManager resourceMan;
\tprivate static CultureInfo resourceCulture;

\t[EditorBrowsable(EditorBrowsableState.Advanced)]
\tpublic static ResourceManager ResourceManager =>
\t\tresourceMan ??= new ResourceManager("{MANIFEST}", typeof(Strings).Assembly);

\t[EditorBrowsable(EditorBrowsableState.Advanced)]
\tpublic static CultureInfo Culture
\t{{
\t\tget => resourceCulture;
\t\tset => resourceCulture = value;
\t}}

{main}}}
}}
"""]
    for ns in sorted(by_ns):
        if ns in (ROOT_NS, ""):
            continue
        fwd = "".join(prop(k, f"global::{ROOT_NS}.Strings.{k}") for k in sorted(by_ns[ns]))
        parts.append(f"""
namespace {ns}
{{
/// <summary>Forwards to <see cref="global::{ROOT_NS}.Strings"/> for files of this namespace.</summary>
internal static class Strings
{{
{fwd}}}
}}
""")
    parts.append("#endif\n")
    path.write_text("".join(parts), encoding="utf-8", newline="\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--atas", type=Path, help="ATAS install folder to take the strings from (use Alpha)")
    src.add_argument("--resx-dir", type=Path, help="folder with OFT.Localization.Strings*.resx")
    args = ap.parse_args()

    by_ns = used_keys()
    keys = sorted(set().union(*by_ns.values()))
    if "" in by_ns:
        print("warning: Strings used in files without a namespace (not shadowed)")
    with tempfile.TemporaryDirectory() as tmp:
        resx_dir = args.resx_dir or extract_from_install(args.atas, Path(tmp))
        files = sorted(resx_dir.rglob(f"{BASE_NAME}*.resx"))
        neutral_file = next((f for f in files if f.name == f"{BASE_NAME}.resx"), None)
        if neutral_file is None:
            sys.exit(f"{BASE_NAME}.resx not found in {resx_dir}")
        neutral = read_resx(neutral_file)
        missing = [k for k in keys if k not in neutral]
        if missing:
            sys.exit(f"keys not found in the source SDK: {', '.join(missing)}")

        OUT_DIR.mkdir(parents=True, exist_ok=True)
        for old in OUT_DIR.glob(f"{RESX_NAME}*"):
            old.unlink()
        write_resx(OUT_DIR / f"{RESX_NAME}.resx", {k: neutral[k] for k in keys})
        cultures = []
        for f in files:
            m = re.fullmatch(re.escape(BASE_NAME) + r"\.([a-z]{2}-[a-z]{2})\.resx", f.name, re.I)
            if not m:
                continue
            culture = m.group(1).lower()
            values = read_resx(f)
            write_resx(OUT_DIR / f"{RESX_NAME}.{culture}.resx", {k: values[k] for k in keys if k in values})
            cultures.append(culture)
        write_code(OUT_DIR / CODE_FILE, by_ns, keys)
    print(f"{len(keys)} keys, cultures: {', '.join(sorted(cultures))} -> {OUT_DIR.relative_to(REPO)}")


if __name__ == "__main__":
    main()
