<#
.SYNOPSIS
    Takes the JSONs generated by the diff script and rebuilds 
    FallbackResources.resx and its satellites in the local project.
#>
param(
    # Using $PSScriptRoot anchors the path to the script's actual location
    [string]$FallbacksDataDir = "$PSScriptRoot\..\..\fallbacks-data",
    [string]$ResxDir = "$PSScriptRoot\..\..\Technical\Properties",
    [string]$BaseName = "FallbackResources"
)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

Add-Type -AssemblyName System.Windows.Forms

# Normalize the paths (Resolves the ..\..\ into a clean absolute path)
$FallbacksDataDir = [System.IO.Path]::GetFullPath($FallbacksDataDir)
$ResxDir = [System.IO.Path]::GetFullPath($ResxDir)

if (-not (Test-Path $ResxDir)) {
    Write-Error "Destination directory does not exist: $ResxDir"
    exit 1
}

function Write-Resx {
    param([string]$File, [hashtable]$Data)
    $writer = New-Object System.Resources.ResXResourceWriter $File
    foreach ($key in $Data.Keys | Sort-Object) {
        $writer.AddResource($key, $Data[$key])
    }
    $writer.Generate()
    $writer.Close()
}

$files = Get-ChildItem "$FallbacksDataDir\fallback_*.json"

foreach ($file in $files) {
    # Extract culture from the filename (e.g., "fallback_es-ES.json" -> "es-ES")
    $culture = $file.BaseName.Replace("fallback_", "")
    
    Write-Host "Writing Resx for: $culture"
    
    $json = Get-Content $file.FullName -Raw -Encoding UTF8 | ConvertFrom-Json
    $table = @{}
    foreach ($prop in $json.PSObject.Properties) {
        $table[$prop.Name] = $prop.Value
    }

    if ($culture -eq "neutral") {
        $resxFile = Join-Path $ResxDir "$BaseName.resx"
    } else {
        $resxFile = Join-Path $ResxDir "$BaseName.$culture.resx"
    }

    Write-Resx -File $resxFile -Data $table
}

Write-Host "Sync completed. Try compiling your project!" -ForegroundColor Green